language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
  - pip install codecov

install:
  - pip install -r development.txt

after_success:
  - codecov

# # command to run tests
script: nosetests -v -s --with-coverage --cover-erase --cover-inclusive test --cover-package=w1thermsensor

notifications:
    webhooks:
    urls:
        - https://webhooks.gitter.im/e/1783c332a0ad247e3476
    on_success: always
    on_failure: always
    on_start: false
addons:
    code_climate:
        repo_token: ff2793d6c31bf4cf431c7f57cca9c745679f16d8c6a7fd78b1c0ca5ec1c68473
